- src/Editor.re
This fixes the "Load" command on Windows - and presumably all the other commands relying on this too.
I can't tell if this breaks anything else though - hopefully not!
> Apply `Parser.filepath` to normalise path retrieved from Editor

- lib/js/src/Editor.bs.js
- src/Editor.re
This small fix allows to load the agda-mode not only for 
.lagda files but also for .lagda.tex, among the others.
> [  fix/Editor ] agda-mode for all .lagda.* files

- lib/js/src/Parser/SourceFile.bs.js
- package.json
- src/Parser/SourceFile.re
This fix allows the user to see easily the available commands by
typing "agda" in the command palette (ctrl+shift+p).
> [ fix ] "Agda:" is now the prefix for all command titles

- package.json
These changes prevent agda mode from "eating" ctrl+u before it makes it to the terminal!
I'm sorry I don't know how to test this locally, but I've made these local changes to my shortcuts file and achieved the desired behavior.
> do not use ctrl+u with terminal focus

- package-lock.json
Reverts banacorn/agda-mode-vscode#64
> [ fix ] Revert "Bump tar from 6.1.8 to 6.1.11"

- lib/js/src/Goal.bs.js
- lib/js/src/Request.bs.js
- src/Goal.res
- src/Request.res
Hello! I ran into an issue a while ago, where trying to elaborate/give expressions in holes that contain strings resulted in lexical errors. These errors did not occur in `agda-mode` for Emacs.
<details>
<summary>Screenshot</summary>
</details>
<details>
<summary>Demo code in the screenshot</summary>
```agda
open import Agda.Builtin.List
open import Agda.Builtin.Nat
open import Agda.Builtin.String
open import Agda.Builtin.Reflection
open import Agda.Builtin.Unit
macro
doAThing : String → Term → TC ⊤
doAThing s h = typeError (strErr "Finished" ∷ [])
thing : Nat
thing = {! doAThing "x"  !}
thing2 : String
thing2 = {! "x"  !}
```
</details>
This only happens when the expression from the hole in the source code is used. If the hole is empty, `agda-mode-vscode` will prompt for an expression, …
> Prevent expressions from being quoted twice

- README.md
Fix the documentation for the case split keymap. It should be `C-c C-c` instead of `C-y C-c`.
PS. Thanks for creating this extension. :)
> Fix the documentation for the case split keymap

- package.json
These settings are user interface settings and should probably not be marked `"machine-overridable"`, so that they can be synced. This makes this extension more consistent with other extensions.
> remove "machine-overridable" scope from some settings

- README.md
Additionally, lines that contained trailing whitespace were trimmed.
> Fix typos of 'Shortcuts' in documentation

- .gitignore
- lib/js/src/Main.bs.js
- lib/js/src/Tokens.bs.js
- package.json
- src/Main.res
- src/Tokens.res
Solving #44 , tested on my machine
I worry that I could break something on other OSes now, so please check if the change is ok! 🥺
The normalizedFileName issue prevented even stepping into the main function. But then, the tokens were wrongly offset because of surrogate pairs. If I had the 𝕊 character inside my agda file it would break - have had it worked on Mac?
> [ fix ] "go to definition" on Windows

- src/Connection/Emacs/Connection__Emacs.res
When switching between projects that use different versions of Agda, I have to clear the agda path and restart vscode every time, which is annoying.
If there is a use case for saving the path in the config, we could expose this as a setting. Or maybe only save when the path is not empty.
I couldn't build rescript on NixOS so I didn't regenerate the javascript.
> Don't store the agda path in the config

- package.json
I adjust the condition of activating input method to enable inputting '\\' into the search box.
> Disable activating input method inside the search box, which is related to issue #79

- style/style.less
Using `C-c C-.` before:
After:
The pane is the same size in both pictures.
I first tried introducing settings to allow users to change the scaling of the pane, but I sadly know too little ReScript.
Anyway, I'm open to change some of the parameters, but the general sentiment is that I think compacting the information in the pane is an improvement.
Resolves #160.
> Compact UI

- language-configuration.json
Defines rules for auto indenting common scenarios where the code must be indented to type check regardless. The only exception where the code doesn't strictly have to be indented is after a `⦃`, but having this indentation rule makes it consistent with the behavior of `(` and `{` and so on.
> Define auto indentation rules

- lib/js/src/State/State__Response.bs.js
- lib/js/src/State/State__View.bs.js
- src/State/State__Response.res
- src/State/State__View.res
The verbosity is removed and the modules being checked are only printed in the Agda buffer.
> Re #90: Debug buffer won't print modules checked and verbosity

- package-lock.json
- package.json
Closes #116 #122. And possibly fixes #86.
Before merging this, it's probably better to get the upstream fixed https://github.com/banacorn/language-server-mule/pull/1 and then update the dependency ref to "v0.2.4" instead of pinning it to a specific commit (like how it is now).
> [ fix ] Update language-server-mule to 0.2.4 (Fixes LSP)

- src/State/State__Command.res
[Emacs-Mode](https://agda.readthedocs.io/en/latest/tools/emacs-mode.html) described about that multiple variables could be case-splitted and should be delimited by whitespaces, but on [plugin store page](https://marketplace.visualstudio.com/items?itemName=banacorn.agda-mode) and inside command editor it wasn't properly described this functionality.
Thus in this PR, I refines the case splitting command description to make users without using Emacs-Mode to know it's possible to case splitting by delimitting variables with whitespaces.
> Add more detailed splitting command description

- lib/js/src/Config.bs.js
- lib/js/src/Main.bs.js
- lib/js/src/View/Singleton.bs.js
- package.json
- src/Config.res
- src/Main.res
- src/View/Singleton.res
- style/style.less
- allow `agdaMode.Buffer.fontSize` to be `null`, and inherit `editor.fontSize` in such a case
- directly getting the panel instance, instead of iterating over the `state` in `Registry`
- the header in the panel also uses the set font size
> Improve the logic related to buffer's font size adjustment

- lib/js/src/View/Root.bs.js
- src/Connection/LSP/Connection__LSP.res
- src/Editor.res
- src/View/Root.res
-  `3:deprecated: ReactDOM.render ReactDOM.render is no longer supported in React 18. Use ReactDOM.Client.createRoot instead.` (https://github.com/banacorn/agda-mode-vscode/blob/ea033d842f5af531e5a48403167a4dac88ced590/src/View/Root.res#L34)
- `33:unused open AgdaModeVscode.Common`
(https://github.com/banacorn/agda-mode-vscode/blob/ea033d842f5af531e5a48403167a4dac88ced590/src/Editor.res#L4)
- `21:this statement never returns (or has an unsound type.)`
(https://github.com/banacorn/agda-mode-vscode/blob/ea033d842f5af531e5a48403167a4dac88ced590/src/Connection/LSP/Connection__LSP.res#L305)
there are several warnings `44:this open statement shadows the module identifier` left. This could be solved by changing `open *` to `open! *` but not sure if this is desirable. So I leave them unchanged
> Address several warnings during build

- CHANGELOG.md
The year for the `0.5.0` version is wrong in the changelog.
> Fix year in CHANGELOG.md

- lib/js/src/Parser/SourceFile.bs.js
- src/Parser/SourceFile.res
Fixes https://github.com/banacorn/agda-mode-vscode/issues/207, fixes https://github.com/banacorn/agda-mode-vscode/issues/205.
As explained in the first linked issue, the `adjustGoalBracket` function used to have no effect because it computed the padding by repeating the empty string, i.e. never added any padding. This was "fixed" in https://github.com/banacorn/agda-mode-vscode/commit/3611495ff8881cdbc14513766a8668be6859bcf8#diff-3802c29909ec1c1d484b9eae9d0c163d290880b5a2b66a197eb2b3b4295f6300L287, which introduced the above two issues. This PR removes `adjustGoalBracket` entirely.
I am not sure why this function was there in the first place.
> [ fix ] Don't add padding to goal brackets

- lib/js/src/Goal.bs.js
- src/Goal.res
The `Interval` constructor will start taking an extra unit argument in 2.8.0, see https://github.com/agda/agda/pull/7610
For searchability, with Agda 2.8.0 (current `master`) and the current version of the extension, trying to give or refine a goal results in errors like
```
Something went wrong when parsing S-expressions. Error code PreprocessError "cannot read: IOTCM "/file.agda" NonInteractive Direct( Cmd_give WithoutForce 0 (intervalsToRange (Just (mkAbsolute "/file.agda")) [Interval (Pn () 216 9 22) (Pn () 218 9 26)]) "x" )"
```
> [ fix ] update Interval format for upcoming 2.8.0

- lib/js/src/Editor.bs.js
- lib/js/src/Parser/SourceFile.bs.js
- lib/js/test/tests/Parser/Test__Parser__SourceFile.bs.js
- package.json
- src/Editor.res
- src/Parser/SourceFile.res
- syntaxes/typst.tmLanguage.json
- test/tests/Parser/Test__Parser__SourceFile.res
Unsure if this is the best way to do it, but I basically extended Markdown support a bit to Typst, considering the syntax is similar. I tested it locally and it worked.
Also, I'm unsure if I should've committed the generated files in `lib/js`.
Let me know if there are changes I should make!
> Basic `lagda.typ` support

- lib/js/src/Parser/SourceFile.bs.js
- lib/js/test/tests/Parser/Test__Parser__SourceFile.bs.js
- package.json
- src/Parser/SourceFile.res
- syntaxes/forester.tmLanguage.json
- syntaxes/org.tmLanguage.json
- syntaxes/restructuredtext.tmLanguage.json
- test/tests/Parser/Test__Parser__SourceFile.res
Also adds missing bindings for literate org files, and renames the scope of reStructuredText to the standard one.
> Add Forester language support

- language-configuration.json
See documentation here: https://agda.readthedocs.io/en/stable/language/syntactic-sugar.html#idiom-brackets
> Add idiom brackets to language configuration

- language-configuration.json
- lib/js/src/Editor.bs.js
- package.json
- src/Editor.res
- syntaxes/forester.tmLanguage.json
- syntaxes/markdown.tmLanguage.json
- syntaxes/org.tmLanguage.json
- syntaxes/restructuredtext.tmLanguage.json
- syntaxes/tex.tmLanguage.json
- syntaxes/typst.tmLanguage.json
Use Agda as an embedded language instead of only using injection grammar. This makes the language configuration only apply within agda blocks, and allows other language configurations to apply elsewhere.
Resolves #223, resolves #108
~Breaks #184 (partially).~
> Agda as an embedded language

- lib/js/src/Tokens.bs.js
- lib/js/src/Util/AVLTree.bs.js
- package-lock.json
- package.json
- src/Util/AVLTree.res
This PR upgrades the dependency providing a BST implementation to v5.3.2, adjusts the interface on our side to fit its breaking change.
This is first step to adopt [this patch](https://github.com/datastructures-js/binary-search-tree/pull/60). I reviewed the code, and thought that adopting an iterative approach is the most prominent way to prevent stack size blowing up on large files.
> Upgrade @datastructures-js/binary-search-tree to v5.3.2

- lib/js/src/Agda.bs.js
- lib/js/src/Editor.bs.js
- lib/js/src/State/State__Response.bs.js
- lib/js/test/tests/TextEditor/Test__AgdaOffset.bs.js
- src/Agda.res
- src/Editor.res
- src/State/State__Response.res
- test/tests/TextEditor/Test__AgdaOffset.res
Fixes https://github.com/banacorn/agda-mode-vscode/issues/216.
Agda and VSCode disagree on how to count characters: Agda uses Unicode code points but treats CRLF as LF, while VSCode [uses](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocuments) UCS-2/UTF-16 code units. This leads to cursor misalignment when jumping to an error. Conveniently, we can just reuse the existing OffsetConverter to fix up the offset.
Also updates some names and comments to clarify that this has nothing to do with UTF-8.
> Fix character offset when jumping to error
